### ISSUE TITLE
Embedded presentations fail due to XSS

### ISSUE THREAD

**Issue by justinnhli** [oxyos/oxyos.github.io#8]
The embedded presentations in the [Resources page](https://oxyos.github.io/resources/) don't load due to cross-site-scripting restrictions. @DyaniDillard @Joey-Rose @NickyBoy89 

![Screenshot_2020-12-14 Oxy Open Source](https://user-images.githubusercontent.com/624737/102171741-17a41d00-3e4c-11eb-93bb-8675546f21ff.jpg)

**Comment by NickyBoy89** [comment]
When I was embedding the slides, I didn't have edit access, so I couldn't embed them properly and added a `/embed` to the URLs of the documents, which, since the original slides are only available to people at Oxy, the iframe tries to sign them in, failing on Incognito and Firefox

Although I am not sure who this is, this can be fixed by the owner of the slides going to each slide, and clicking `File > Publish to the Web > Embed tab`, and replacing the existing links in the `src/app/templates/pages/resources.html` file with the new embed links

**Comment by justinnhli** [comment]
@Joey-Rose @DyaniDillard ?

**Comment by Joey-Rose** [comment]
@justinnhli is it fixed now?

**Comment by justinnhli** [comment]
Yes!

![image](https://user-images.githubusercontent.com/624737/102566698-e23e4000-4094-11eb-8717-b4979ea910b7.png)

Closing.
